AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda function to delete old log streams'

Parameters:
  Project:
    Description: The project name.
    Type: String
  SourceCode:
    Description: The source code.
    Type: String
  Handler:
    Description: The name of the handler function
    Type: String
  Runtime:
    Description: The runtime (e.g. Python or Node etc.)
    Type: String
  MemorySize:
    Description: The amount of memory that the function has access to.
    Type: Number
    Default: 128
  Timeout:
    Description: The amount of time that the function is allowed to run before being stopped.
    Type: Number
    Default: 20
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain log events.'
    Type: Number
    Default: 400
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  ScheduleCron:
    Description: The cron expression for scheduling (UTC timezone)
    Type: String
  ScheduleState:
    Description: Enable or disable scheduling
    Type: String
    AllowedValues: [ENABLED, DISABLED]
#  AlarmNotificationsStack:
#    Description: Stack name of alarm notifications.
#    Type: String

Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: IAM-Permissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:DeleteLogStream'
                Resource: '*'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: 'Perform maintenance: delete old log streams'
      Architectures:
        - arm64
      Code:
        ZipFile: !Ref SourceCode
      Handler: !Ref Handler
      Runtime: !Ref Runtime
      MemorySize: !Ref MemorySize
      Role: !GetAtt LambdaFunctionRole.Arn
      Timeout: !Ref Timeout
      Tags:
        - Key: Project
          Value: !Ref Project

  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      # Logs for Lambda function must follow a specific schema
      LogGroupName: !Join ['', ['/aws/lambda/', !Ref LambdaFunction]]
      RetentionInDays: !Ref LogsRetentionInDays

  SchedulerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt LambdaFunction.Arn
      Principal: events.amazonaws.com

  Scheduler:
    Type: AWS::Events::Rule
    Properties:
      Description: AWS related maintenance
      ScheduleExpression: !Ref ScheduleCron
      State: !Ref ScheduleState
      Targets:
        - Id: !Ref LambdaFunction
          Arn: !GetAtt LambdaFunction.Arn

#  LambdaError:
#    Type: AWS::CloudWatch::Alarm
#    Properties:
#      AlarmDescription: Errors in Lambda function
#      ActionsEnabled: true
#      Namespace: AWS/Lambda
#      Dimensions:
#        - Name: FunctionName
#          Value: !Ref LambdaFunction
#      MetricName: Errors
#      Statistic: Sum
#      ComparisonOperator: GreaterThanOrEqualToThreshold
#      Threshold: 1.0
#      EvaluationPeriods: 1
#      DatapointsToAlarm: 1
#      Period: 60
#      TreatMissingData: notBreaching
#      AlarmActions:
#        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'
#
#  LambdaThrottles:
#    Type: AWS::CloudWatch::Alarm
#    Properties:
#      AlarmDescription: Throttles in Lambda function
#      ActionsEnabled: true
#      Namespace: AWS/Lambda
#      Dimensions:
#        - Name: FunctionName
#          Value: !Ref LambdaFunction
#      MetricName: Throttles
#      Statistic: Sum
#      ComparisonOperator: GreaterThanOrEqualToThreshold
#      Threshold: 1.0
#      EvaluationPeriods: 1
#      DatapointsToAlarm: 1
#      Period: 60
#      TreatMissingData: notBreaching
#      AlarmActions:
#        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

Outputs:
  Name:
    Description: 'Name'
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-Name'
  Arn:
    Description: 'Arn'
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
