AWSTemplateFormatVersion: '2010-09-09'
Description: Notifications about alarms

Parameters:
  EmailAddress:
    Description: The email address notifications should be sent to.
    Type: String

Resources:
  AlarmTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref EmailAddress

Outputs:
  Arn:
    Description: Arn
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
