AWSTemplateFormatVersion: '2010-09-09'
Description: 'Image builder recipe to build GPU AMI'

Parameters:
  ParentImage:
    Description: The parent machine image ID
    Type: String
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  Project:
    Description: The project name.
    Type: String

Resources:
  ImageBuilderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder

  ImageBuilderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ImageBuilderRole

  ImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: GPU-ECS-optimized
      Description: Recommended GPU-ECS-optimized image with encrypted EBS, resized to 200 GB.
      AdditionalInstanceConfiguration:
        SystemsManagerAgent:
          UninstallAfterBuild: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            Encrypted: true
            KmsKeyId: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ebs'
            VolumeSize: 200
            VolumeType: gp3
      Components:
        -  ComponentArn: !Sub 'arn:aws:imagebuilder:${AWS::Region}:aws:component/update-linux/x.x.x'
        -  ComponentArn: !Sub 'arn:aws:imagebuilder:${AWS::Region}:aws:component/simple-boot-test-linux/x.x.x'
      ParentImage: !Ref ParentImage
      Version: 1.0.0
      WorkingDirectory: /tmp
      Tags:
        Project: !Ref Project

  InfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: GPU-ECS-optimized
      InstanceProfileName: !Ref ImageBuilderInstanceProfile
      InstanceTypes:
        - g5.xlarge
      SecurityGroupIds:
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPublic'
      TerminateInstanceOnFailure: true
      ResourceTags:
        Project: !Ref Project
      Tags:
        Project: !Ref Project

  DistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: GPU-ECS-optimized
      Description: Recommended GPU-ECS-optimized image with encrypted EBS, resized to 200 GB.
      Distributions:
        - Region: !Sub '${AWS::Region}'
          AmiDistributionConfiguration: {}
      Tags:
        Project: !Ref Project

  ImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: GPU-ECS-optimized
      Description: An AMI to be used for tasks which require an GPU and must be compatible to ECS, e.g. for using in AWS Batch jobs. The only difference to the recommended, original image is that this image has an encrypted and larger root volume.
      DistributionConfigurationArn: !Ref DistributionConfiguration
      ImageRecipeArn: !Ref ImageRecipe
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: 720
      InfrastructureConfigurationArn: !Ref InfrastructureConfiguration
      Tags:
        Project: !Ref Project


Outputs:
  ImagePipeline:
    Description: ARN of image pipeline
    Value: !Ref ImagePipeline
    Export:
      Name: !Sub '${AWS::StackName}-ImagePipeline'
