AWSTemplateFormatVersion: '2010-09-09'
Description: 'Batch job for AWS Batch to run this application'

Parameters:
  Project:
    Description: The project name.
    Type: String
  User:
    Description: The user name.
    Type: String
  ApplicationName:
    Description: The name of the application
    Type: String
  DockerImage:
    Description: The docker image to run.
    Type: String
  StorageBucketStack:
    Description: The stack name of the stack which set up the S3 bucket to store the data.
    Type: String
  DbHostname:
    Description: The host name of the database
    Type: String
  DbPort:
    Description: The port of the database
    Type: String
  DbDatabase:
    Description: The name of the database
    Type: String
  DbUsername:
    Description: The user name to access the database
    Type: String
  DbPasswordParam:
    Description: The parameter name in Systems Manager containing the password for the database
    Type: String
  LogGroupRetentionTime:
    Description: The rentention time in days.
    Type: Number
    Default: 731
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  ScheduleCron:
    Description: The cron expression for scheduling (UTC timezone)
    Type: String
  ScheduleState:
    Description: Enable or disable scheduling
    Type: String
    AllowedValues: [ENABLED, DISABLED]
  Timeout:
    Description: The maximum time the application may run (in seconds)
    Type: Number
    Default: 120
  ExecutionAttempts:
    Description: The number of attempts to run the application (2 = one retry, 3 = two retries etc.)
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
  JobQueue:
    Description: The job queue to use for running the application; use OnDemand for jobs taking more than 3 minutes
    Type: String
    AllowedValues: [Spot, SpotArm, OnDemand, OnDemandArm]
    Default: Spot
  Memory:
    Description: The amount of memory the container may allocate (in MBytes, default is 2 GBytes).
    Type: Number
    Default: 2048
  Vcpus:
    Description: The number of vCPUs reserved for the container.
    Type: Number
    MinValue: 1
    Default: 1
  BatchQueueStack:
    Description: The stack name of the stack which provisioned the Batch queue.
    Type: String
  AlarmNotificationsStack:
    Description: Stack name of alarm notifications.
    Type: String

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref LogGroupRetentionTime

  JobTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Read-Storage
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetBucketLocation'
                  - 's3:ListBucket'
                Resource:
                  - 'Fn::ImportValue': !Sub '${StorageBucketStack}-Arn'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource:
                  - !Join [ '', [ 'Fn::ImportValue': !Sub '${StorageBucketStack}-Arn', '/*' ]]
        - PolicyName: Read-Credentials
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${DbPasswordParam}'
        - PolicyName: Save-metrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
                Condition:
                  StringEquals:
                    'cloudwatch:namespace': !Sub 'App/${ApplicationName}'

  Job:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      ContainerProperties:
        Image: !Ref DockerImage
        Memory: !Ref Memory
        Vcpus: !Ref Vcpus
        Environment:
          - Name: STORAGE_BUCKET
            Value:
              'Fn::ImportValue': !Sub '${StorageBucketStack}-BucketName'
          - Name: DB_HOSTNAME
            Value: !Ref DbHostname
          - Name: DB_PORT
            Value: !Ref DbPort
          - Name: DB_DATABASE
            Value: !Ref DbDatabase
          - Name: DB_USERNAME
            Value: !Ref DbUsername
          - Name: DB_PASSWORD_PARAM
            Value: !Ref DbPasswordParam
          - Name: LOG_GROUP
            Value: !Ref LogGroup
          - Name: METRICS_NAMESPACE
            Value: !Sub 'App/${ApplicationName}'
        JobRoleArn: !Ref JobTaskRole
        LogConfiguration:
          LogDriver: awslogs
          Options:
            'awslogs-group': !Ref LogGroup
      RetryStrategy:
        Attempts: !Ref ExecutionAttempts
      Timeout:
        AttemptDurationSeconds: !Ref Timeout

  ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '{$.level = ERROR || $.level = FATAL}'
      LogGroupName: !Ref LogGroup
      MetricTransformations:
        - MetricName: Errors
          MetricNamespace: !Sub 'App/${ApplicationName}'
          MetricValue: 1
          DefaultValue: 0

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub '${ApplicationName} reported an error'
      ActionsEnabled: true
      Namespace: !Sub 'App/${ApplicationName}'
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 300
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

  StateMachinePermissions:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Execute-Batch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'batch:SubmitJob'
                  - 'batch:DescribeJobs'
                  - 'batch:TerminateJob'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'events:PutTargets'
                  - 'events:PutRule'
                  - 'events:DescribeRule'
                Resource: !Sub 'arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForBatchJobsRule'

  StateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Ref ApplicationName
      DefinitionString:
        !Sub
        - |-
          {
            "StartAt": "Execute",
            "States": {
              "Execute": {
                "Type": "Task",
                "Resource": "arn:aws:states:::batch:submitJob.sync",
                "Parameters": {
                  "JobName": "ExecuteBatchJob",
                  "JobDefinition": "${JobDefinitionArn}",
                  "JobQueue": "${JobQueueArn}"
                },
                "End": true
              }
            }
          }
        - JobDefinitionArn: !Ref Job
          JobQueueArn:
            'Fn::ImportValue': !Sub '${BatchQueueStack}-${JobQueue}Queue-Arn'
      RoleArn: !GetAtt StateMachinePermissions.Arn
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: User
          Value: !Ref User

  ExecuteStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Execute-Step-Functions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource: !Ref StateMachine

  Rule:
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub 'Run ${ApplicationName} regularly'
      ScheduleExpression: !Ref ScheduleCron
      State: !Ref ScheduleState
      Targets:
        - Arn: !Ref StateMachine
          Id: !Sub 'Schedule-${ApplicationName}'
          RoleArn: !GetAtt ExecuteStepFunctionsRole.Arn

  ExecutionsFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: StepFunctions execution failed
      ActionsEnabled: true
      Namespace: AWS/States
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref StateMachine
      MetricName: ExecutionsFailed
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 60
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

  ExecutionsTimedOut:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: StepFunctions execution timed out
      ActionsEnabled: true
      Namespace: AWS/States
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref StateMachine
      MetricName: ExecutionsTimedOut
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 60
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

  ExecutionsAborted:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: StepFunctions execution aborted
      ActionsEnabled: true
      Namespace: AWS/States
      Dimensions:
        - Name: StateMachineArn
          Value: !Ref StateMachine
      MetricName: ExecutionsAborted
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 60
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'


Outputs:
  Job:
    Value: !Ref Job
    Description: Job ARN
    Export:
      Name: !Sub '${AWS::StackName}-Job'
  StateMachine:
    Value: !Ref StateMachine
    Description: State Machine ARN
    Export:
      Name: !Sub '${AWS::StackName}-StateMachine'
