AWSTemplateFormatVersion: '2010-09-09'
Description: 'Compute environments for AWS Batch'

Parameters:
  Project:
    Description: The project name.
    Type: String
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String

Resources:
  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: batch.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  BatchInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  BatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BatchInstanceRole

  SpotFleetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: spotfleet.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2SpotFleetTaggingRole

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for AWS Batch instances
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      Tags:
        - Key: Project
          Value: !Ref Project

  InstanceSecurityGroupSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: -1
      SourceSecurityGroupId: !Ref InstanceSecurityGroup

  InstanceSecurityGroupSelfEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: -1
      DestinationSecurityGroupId: !Ref InstanceSecurityGroup

  Ec2OnDemandX86Environment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeResources:
        Type: EC2
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        MinvCpus: 0
        MaxvCpus: 256
        DesiredvCpus: 0
        InstanceTypes:
          - m5
        InstanceRole: !Ref BatchInstanceProfile
        Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'  # Access to VPC endpoints
        UpdateToLatestImageVersion: true
        Tags:
          Project: !Ref Project
      ReplaceComputeEnvironment: false
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED
      Type: MANAGED

  Ec2OnDemandX86Queue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref Ec2OnDemandX86Environment
      State: ENABLED
      Priority: 1

  Ec2OnDemandArmEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeResources:
        Type: EC2
        AllocationStrategy: BEST_FIT_PROGRESSIVE
        MinvCpus: 0
        MaxvCpus: 256
        DesiredvCpus: 0
        InstanceTypes:
          - m6g
        InstanceRole: !Ref BatchInstanceProfile
        Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'  # Access to VPC endpoints
        UpdateToLatestImageVersion: true
        Tags:
          Project: !Ref Project
      ReplaceComputeEnvironment: false
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED
      Type: MANAGED

  Ec2OnDemandArmQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref Ec2OnDemandArmEnvironment
      State: ENABLED
      Priority: 1

  Ec2SpotX86Environment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeResources:
        Type: SPOT
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        SpotIamFleetRole: !Ref SpotFleetRole
        MinvCpus: 0
        MaxvCpus: 256
        DesiredvCpus: 0
        InstanceTypes:
          - m5
        InstanceRole: !Ref BatchInstanceProfile
        Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'  # Access to VPC endpoints
        UpdateToLatestImageVersion: true
        Tags:
          Project: !Ref Project
      ReplaceComputeEnvironment: false
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED
      Type: MANAGED

  Ec2SpotX86Queue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref Ec2SpotX86Environment
      State: ENABLED
      Priority: 1

  Ec2SpotArmEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeResources:
        Type: SPOT
        AllocationStrategy: SPOT_CAPACITY_OPTIMIZED
        BidPercentage: 100
        SpotIamFleetRole: !Ref SpotFleetRole
        MinvCpus: 0
        MaxvCpus: 256
        DesiredvCpus: 0
        InstanceTypes:
          - m6g
        InstanceRole: !Ref BatchInstanceProfile
        Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'  # Access to VPC endpoints
        UpdateToLatestImageVersion: true
        Tags:
          Project: !Ref Project
      ReplaceComputeEnvironment: false
      ServiceRole: !GetAtt BatchServiceRole.Arn
      State: ENABLED
      Type: MANAGED

  Ec2SpotArmQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref Ec2SpotArmEnvironment
      State: ENABLED
      Priority: 1

  FargateOnDemandEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeResources:
        Type: FARGATE
        MaxvCpus: 256
        # Do not use all private subnets, only subnet A as this is the only subnet with a NAT gateway
        # Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
        Subnets:
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'  # Access to VPC endpoints
      State: ENABLED
      Type: MANAGED

  FargateOnDemandQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref FargateOnDemandEnvironment
      State: ENABLED
      Priority: 1

  FargateSpotEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeResources:
        Type: FARGATE_SPOT
        MaxvCpus: 256
        # Do not use all private subnets, only subnet A as this is the only subnet with a NAT gateway
        # Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPublic'}]
        Subnets:
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-CustomDefaultSecurityGroup'  # Access to VPC endpoints
      State: ENABLED
      Type: MANAGED

  FargateSpotQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref FargateSpotEnvironment
      State: ENABLED
      Priority: 1


Outputs:
  Ec2OnDemandX86Queue:
    Value: !Ref Ec2OnDemandX86Queue
    Description: ARN of queue with EC2 machines with X86 architecture
    Export:
      Name: !Sub '${AWS::StackName}-Ec2OnDemandX86Queue-Arn'
  Ec2OnDemandArmQueue:
    Value: !Ref Ec2OnDemandArmQueue
    Description: ARN of queue with EC2 machines with ARM architecture
    Export:
      Name: !Sub '${AWS::StackName}-Ec2OnDemandArmQueue-Arn'
  Ec2SpotX86Queue:
    Value: !Ref Ec2SpotX86Queue
    Description: ARN of queue with EC2 spot machines with X86 architecture
    Export:
      Name: !Sub '${AWS::StackName}-Ec2SpotX86Queue-Arn'
  Ec2SpotArmQueue:
    Value: !Ref Ec2SpotArmQueue
    Description: ARN of queue with EC2 spot machines with ARM architecture
    Export:
      Name: !Sub '${AWS::StackName}-Ec2SpotArmQueue-Arn'
  InstanceSecurityGroup:
    Description: Security group ID of EC2 instance
    Value: !GetAtt InstanceSecurityGroup.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-InstanceSecurityGroupId'
  FargateOnDemandX86Queue:
    Value: !Ref FargateOnDemandQueue
    Description: ARN of queue with Fargate management
    Export:
      Name: !Sub '${AWS::StackName}-FargateOnDemandX86Queue-Arn'
  FargateSpotX86Queue:
    Value: !Ref FargateSpotQueue
    Description: ARN of queue with Fargate Spot management
    Export:
      Name: !Sub '${AWS::StackName}-FargateSpotX86Queue-Arn'
  FargateOnDemandArmQueue:
    Value: !Ref FargateOnDemandQueue
    Description: ARN of queue with Fargate management
    Export:
      Name: !Sub '${AWS::StackName}-FargateOnDemandArmQueue-Arn'
  FargateSpotArmQueue:
    Value: !Ref FargateSpotQueue
    Description: ARN of queue with Fargate Spot management
    Export:
      Name: !Sub '${AWS::StackName}-FargateSpotArmQueue-Arn'
