AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway'

Parameters:
  Project:
    Description: The project name.
    Type: String
  User:
    Description: The user name.
    Type: String
  ApiName:
    Description: The name of the API
    Type: String
  ApiDomainName:
    Description: The name of the API domain
    Type: String
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain log events.'
    Type: Number
    Default: 7
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  AlarmThreshold:
    Description: Trigger an alarm if more than x requests within a minute failed
    Type: Number
    Default: 1
  AlarmNotificationsStack:
    Description: Stack name of alarm notifications.
    Type: String
  DomainCertificate:
    Description: The ARN of the domain certificate (on region level)
    Type: String
  Route53HostedZone:
    Description: The Route53 hosted zone ID
    Type: String
  SecondaryDomainCertificate:
    Description: The ARN of the secondary domain certificate (on region level)
    Type: String
  SecondaryRoute53HostedZone:
    Description: The secondary Route53 hosted zone ID
    Type: String
  SecondaryApiDomainName:
    Description: The name of the secondary API domain
    Type: String

Conditions:
  DeploySecondaryApiGateway: !Not [!Equals [!Ref SecondaryRoute53HostedZone, '']]

Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiName
      ProtocolType: HTTP
      Tags:
        Project: !Ref Project

  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref LogsRetentionInDays

  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      AccessLogSettings:
        DestinationArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${Logs}'
        Format: '{ "requestId":"$context.requestId", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","routeKey":"$context.routeKey", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength", "errorMessage":"$context.error.message" }'
      ApiId: !Ref Api
      AutoDeploy: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: false
      StageName: '$default'
      Tags:
        Project: !Ref Project

  Domain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref ApiDomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref DomainCertificate
          EndpointType: REGIONAL
      Tags:
        Project: !Ref Project

  SecondaryDomain:
    Condition: DeploySecondaryApiGateway
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !Ref SecondaryApiDomainName
      DomainNameConfigurations:
        - CertificateArn: !Ref SecondaryDomainCertificate
          EndpointType: REGIONAL
      Tags:
        Project: !Ref Project

  DomainMapping:
    DependsOn: DnsRecordSet
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref Api
      DomainName: !Ref ApiDomainName
      Stage: !Ref ApiStage

  SecondaryDomainMapping:
    Condition: DeploySecondaryApiGateway
    DependsOn: SecondaryDnsRecordSet
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref Api
      DomainName: !Ref SecondaryApiDomainName
      Stage: !Ref ApiStage

  Alarm5xx:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Too many 5xx responses
      ActionsEnabled: true
      Namespace: AWS/ApiGateway
      Dimensions:
        - Name: ApiId
          Value: !Ref Api
      MetricName: 5xx
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: !Ref AlarmThreshold
      EvaluationPeriods: 10
      DatapointsToAlarm: 8
      Period: 60
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

  DnsRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt Domain.RegionalDomainName
        HostedZoneId: !GetAtt Domain.RegionalHostedZoneId
      HostedZoneId: !Ref Route53HostedZone
      Name: !Ref Domain
      Type: A

  SecondaryDnsRecordSet:
    Condition: DeploySecondaryApiGateway
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt SecondaryDomain.RegionalDomainName
        HostedZoneId: !GetAtt SecondaryDomain.RegionalHostedZoneId
      HostedZoneId: !Ref SecondaryRoute53HostedZone
      Name: !Ref SecondaryDomain
      Type: A

Outputs:
  Api:
    Description: API ID
    Value: !Ref Api
    Export:
      Name: !Sub '${AWS::StackName}-Api'
  ApiGatewayDomain:
    Description: 'API Gateway domain name'
    Value: !GetAtt Domain.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-ApiGatewayDomain'
  Domain:
    Description: 'Domain name'
    Value: !Ref DnsRecordSet
    Export:
      Name: !Sub '${AWS::StackName}-Domain'
  SecondaryApiGatewayDomain:
    Condition: DeploySecondaryApiGateway
    Description: 'Secondary API Gateway domain name'
    Value: !GetAtt SecondaryDomain.RegionalDomainName
    Export:
      Name: !Sub '${AWS::StackName}-SecondaryApiGatewayDomain'
  SecondaryDomain:
    Condition: DeploySecondaryApiGateway
    Description: 'Secondary Domain name'
    Value: !Ref SecondaryDnsRecordSet
    Export:
      Name: !Sub '${AWS::StackName}-SecondaryDomain'
  Logs:
    Description: 'Logs ARN'
    Value: !GetAtt Logs.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Logs'
