AWSTemplateFormatVersion: '2010-09-09'
Description: 'API Gateway'

Parameters:
  Project:
    Description: The project name.
    Type: String
  User:
    Description: The user name.
    Type: String
  ApiGatewayPath:
    Description: The path of the API
    Type: String
  Timeout:
    Description: The amount of time to wait for Lambda function (in milliseconds).
    Type: Number
    Default: 29000
  LambdaArn:
    Description: The ARN of the Lambda function
    Type: String
  ApiStack:
    Description: Stack name of API Gateway stack.
    Type: String

Resources:
  InvokeLambdaPermissions:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowLambdaInvoke
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !Ref LambdaArn
                  - !Sub '${LambdaArn}:Active'

  ApiToLambda:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        'Fn::ImportValue': !Sub '${ApiStack}-Api'
      ConnectionType: INTERNET
      CredentialsArn: !GetAtt InvokeLambdaPermissions.Arn
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}:Active/invocations'
      PayloadFormatVersion: 2.0
      TimeoutInMillis: !Ref Timeout

  Ratings:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        'Fn::ImportValue': !Sub '${ApiStack}-Api'
      RouteKey: !Sub 'ANY /${ApiGatewayPath}'
      Target: !Sub 'integrations/${ApiToLambda}'

Outputs:
  Url:
    Description: 'URL'
    Value: !Join [ '', [ 'https://', 'Fn::ImportValue': !Sub '${ApiStack}-Domain', !Sub '/${ApiGatewayPath}' ]]
    Export:
      Name: !Sub '${AWS::StackName}-Url'