AWSTemplateFormatVersion: '2010-09-09'
Description: 'SQS Queue'

Parameters:
  Project:
    Description: The project name
    Type: String
  QueueName:
    Description: The name of the Queue
    Type: String

Resources:
  ProcessQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
      DelaySeconds: 2
      MessageRetentionPeriod: 3600
      RedrivePolicy:
        deadLetterTargetArn: !Sub ${DeadLetterQueue.Arn}
        maxReceiveCount: 10
  DeadLetterQueue:
    Type: AWS::SQS::Queue

Outputs:
  Arn:
    Description: 'Arn'
    Value: !GetAtt ProcessQueue.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
  Url:
    Description: 'Url'
    Value: !Ref ProcessQueue
    Export:
      Name: !Sub '${AWS::StackName}-Url'
