AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mappings between SQS and Lambda Functions.'

Parameters:
  Project:
    Description: The project name
    Type: String
  ProcessQueueArn:
    Description: The Queue that provides the Events
    Type: String
  ProcessLambdaArn:
    Description: The Function that processes the Events
    Type: String
  BatchSize:
    Description: Specifies the Batch Size
    Type: Number
    Default: 32
  BatchingWindow:
    Description: Maximum Batch Window in Seconds
    Type: Number
    Default: 1

Resources:
  ProcessEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !Ref ProcessQueueArn
      FunctionName: !Ref ProcessLambdaArn
      BatchSize: !Ref BatchSize
      MaximumBatchingWindowInSeconds: !Ref BatchingWindow
