AWSTemplateFormatVersion: '2010-09-09'
Description: Service Discovery to allow Docker containers find their services

Parameters:
  DnsName:
    Description: The DNS name
    Type: String
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  Project:
    Description: The project name.
    Type: String

Resources:
  Namespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Description: Service discovery for internal access
      Name: !Ref DnsName
      Vpc:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      Tags:
        - Key: Project
          Value: !Ref Project


Outputs:
  Arn:
    Description: Namespace ARN
    Value: !GetAtt Namespace.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
  Id:
    Description: Namespace ID
    Value: !Ref Namespace
    Export:
      Name: !Sub '${AWS::StackName}-Id'
