AWSTemplateFormatVersion: '2010-09-09'
Description: 'MySQL serverless database'

Parameters:
  ClusterOnly:
    Description: Provision the cluster only, do not create a database instance
    Type: String
    AllowedValues: ['true', 'false']
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  DBName:
    Description: 'The database name'
    Type: String
    MinLength: 1
    MaxLength: 8
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'must begin with a letter and contain only alphanumeric characters.'
  DBUsername:
    Description: 'The database admin account username'
    Type: String
    Default: 'root'
    NoEcho: true
  DBPassword:
    Description: 'The database admin account password'
    Type: String
    NoEcho: true
  BackupRetentionPeriod:
    Description: 'The number of days for which automated backups are retained. 0 disabled automated backups.'
    Type: String
    Default: '7'
    AllowedValues: ['0', '1', '7']
    ConstraintDescription: 'must select a valid backup retention period.'
  Project:
    Description: The project name.
    Type: String

Conditions:
  ProvisionDatabaseInstance: !Equals [!Ref ClusterOnly, 'false']

Resources:
  DatabaseAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for database
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      Tags:
        - Key: Project
          Value: !Ref Project

  DatabaseAccessSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DatabaseAccess
      IpProtocol: -1
      SourceSecurityGroupId: !Ref DatabaseAccess

  DatabaseAccessSelfEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref DatabaseAccess
      IpProtocol: -1
      DestinationSecurityGroupId: !Ref DatabaseAccess

  PrivateSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 'Private subnet'
      SubnetIds: !Split
        - ','
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'

  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DatabaseName: !Ref DBName
      DBClusterParameterGroupName: default.aurora-mysql8.0
      DBSubnetGroupName: !Ref PrivateSubnetGroup
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - slowquery
      Engine: aurora-mysql
      EngineMode: provisioned
      EngineVersion: 8.0.mysql_aurora.3.02.0
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PreferredBackupWindow: '22:22-22:52'
      PreferredMaintenanceWindow: 'sat:10:00-sat:18:00'
      # ScalingConfiguration not support by CloudFormation yet for Aurora Serverless v2
      StorageEncrypted: true
      VpcSecurityGroupIds:
        - !Ref DatabaseAccess
      Tags:
        - Key: Project
          Value: !Ref Project

  PrimaryInstance:
    Type: AWS::RDS::DBInstance
    Condition: ProvisionDatabaseInstance
    Properties:
      CACertificateIdentifier: 'rds-ca-2019'
      DBClusterIdentifier: !Ref Cluster
      DBInstanceClass: db.serverless
      DBParameterGroupName: default.aurora-mysql8.0
      EnablePerformanceInsights: true
      Engine: aurora-mysql
      MonitoringInterval: 60
      MonitoringRoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/rds-monitoring-role'
      PerformanceInsightsRetentionPeriod: 7
      PreferredMaintenanceWindow: 'tue:00:10-tue:00:40'
      Tags:
        - Key: Project
          Value: !Ref Project


Outputs:
  Hostname:
    Description: Hostname of database
    Value: !GetAtt Cluster.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-Hostname'
  Port:
    Description: Port of database
    Value: !GetAtt Cluster.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-Port'
  ReadHostname:
    Description: Reader endpoint of database
    Value: !GetAtt Cluster.ReadEndpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-ReadHostname'
  ClusterID:
    Description: Cluster ID
    Value: !Ref Cluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterID'
  DatabaseAccess:
    Description: Security group to access the database
    Value: !GetAtt DatabaseAccess.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseAccess'
