AWSTemplateFormatVersion: '2010-09-09'
Description: 'Sagemaker Jupyter notebook'

Parameters:
  Project:
    Description: The project name.
    Type: String
  GoogleCredentialsName:
    Description: The parameter name in Systems Manager containing the Google credentials
    Type: String
  InstanceType:
    Description: The instance type powering the notebook machine
    Type: String
    Default: ml.t3.medium
  VolumeSize:
    Description: The size of the storage volume
    Type: Number
    Default: 5
    MinValue: 5
    MaxValue: 16384
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  DatabaseStack:
    Description: The stack name of the database stack.
    Type: String

Resources:
  NotebookRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Read-passwords
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${GoogleCredentialsName}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess

  Notebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      DirectInternetAccess: Disabled
      InstanceType: !Ref InstanceType
      RoleArn: !GetAtt NotebookRole.Arn
      SecurityGroupIds:
        - 'Fn::ImportValue': !Sub '${DatabaseStack}-DBInstanceSecurityGroupId'  # Access to database
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetCPrivate'  # Take private subnet with the highest IP number
        # as Sagemaker will create another network interface right after this IP range.
      VolumeSizeInGB: !Ref VolumeSize
      Tags:
        - Key: Project
          Value: !Ref Project


Outputs:
  Name:
    Value: !GetAtt Notebook.NotebookInstanceName
    Description: Notebook instance name
    Export:
      Name: !Sub '${AWS::StackName}-Name'
