AWSTemplateFormatVersion: '2010-09-09'
Description: 'Docker repository in ECR'

Parameters:
  Name:
    Description: The repository name
    Type: String
  Project:
    Description: The project name.
    Type: String

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref Name
      LifecyclePolicy:
        LifecyclePolicyText: |-
          {
            "rules": [
              {
                "action": {
                  "type": "expire"
                },
                "selection": {
                  "countType": "sinceImagePushed",
                  "countNumber": 14,
                  "countUnit": "days",
                  "tagStatus": "untagged"
                },
                "description": "Expire untagged images older than 14 days",
                "rulePriority": 1
              }
            ]
          }
      Tags:
        - Key: Project
          Value: !Ref Project

Outputs:
  Uri:
    Description: Repository URI
    Value: !GetAtt Repository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-Uri'
