AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mailpit Docker container'

Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  LogGroupRetentionTime:
    Description: The retention time in days.
    Type: Number
    Default: 731
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  Hostname:
    Description: The hostname of the Mailpit instance
    Type: String
  DockerImage:
    Description: The docker image to run.
    Type: String
  ServiceDiscoveryName:
    Description: The name under which this service will be registered at Service Discovery
    Type: String
  Cpu:
    Description: The number of CPU units used by this application. 1024 is equivalent to 1 CPU.
    Type: String
    AllowedValues: [256, 512, 1024, 2048, 4096]
  Memory:
    Description: The memory (in MBytes) to allocate for this application.
    Type: String
  LoadBalancerRulePriority:
    Description: The priority of the rule for this application within the load balancer configuration (can be a random number, but must be unique)
    Type: Number
  ContainerClusterAlbStack:
    Description: Stack name of Fargate container stack
    Type: String
  ServiceDiscoveryStack:
    Description: Stack name of service discovery stack
    Type: String
  Environment:
    Description: The current environment (e.g. branch name)
    Type: String
  Project:
    Description: The project name.
    Type: String

Resources:
  VolumeAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to access volumes
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      Tags:
        - Key: Project
          Value: !Ref Project

  VolumeAccessSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref VolumeAccess
      IpProtocol: -1
      SourceSecurityGroupId: !Ref VolumeAccess

  VolumeAccessSelfEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref VolumeAccess
      IpProtocol: -1
      DestinationSecurityGroupId: !Ref VolumeAccess

  DataVolume:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: !Sub 'Mailpit Data ${Environment}'
        - Key: Project
          Value: !Ref Project

  DataVolumeMountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref DataVolume
      SecurityGroups:
        - !GetAtt VolumeAccess.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'

  DataVolumeMountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref DataVolume
      SecurityGroups:
        - !GetAtt VolumeAccess.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPrivate'

  DataVolumeMountTargetC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref DataVolume
      SecurityGroups:
        - !GetAtt VolumeAccess.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetCPrivate'

# No need to enforce www-data/www-data as owner
#  DataVolumeAccessPoint:
#    # Ensure specific UID/GID as Mailpit installation will fail when trying to set owner on its own
#    Type: AWS::EFS::AccessPoint
#    Properties:
#      FileSystemId: !Ref DataVolume
#      PosixUser:
#        Gid: "33"
#        Uid: "33"
#      RootDirectory:
#        CreationInfo:
#          OwnerGid: "33"
#          OwnerUid: "33"
#          Permissions: "755"
#        Path: /html
#      AccessPointTags:
#        - Key: Project
#          Value: !Ref Project

# Application does not need any access to AWS services; uncomment block if required
#  ApplicationTaskRole:
#    Type: AWS::IAM::Role
#    Properties:
#      Description: Application's permissions
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service: ecs-tasks.amazonaws.com
#            Action: sts:AssumeRole
#      ManagedPolicyArns:
#          # Allow full access as Mailpit uses separate UID and GID
#          # See https://aws.amazon.com/de/blogs/containers/developers-guide-to-using-amazon-efs-with-amazon-ecs-and-aws-fargate-part-3/
#          # for detailed instructions
#        - arn:aws:iam::aws:policy/AmazonElasticFileSystemClientFullAccess

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Provides access to other AWS service resources that are required to run Amazon ECS tasks
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref LogGroupRetentionTime

  ApplicationTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - DataVolumeMountTargetA
      - DataVolumeMountTargetB
      - DataVolumeMountTargetC
    Properties:
      ContainerDefinitions:
        - Name: Mailpit
          Image: !Ref DockerImage
          Environment:
            - Name: MP_DATA_FILE
              Value: /data/maildata.sqlite
            - Name: MP_MAX_MESSAGES
              Value: 500
            - Name: MP_UI_AUTH_FILE
              Value: /etc/mailpit_basic_auth.txt
          MountPoints:
            - ContainerPath: /data
              SourceVolume: Data
          PortMappings:
            - ContainerPort: 1025
            - ContainerPort: 8025
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              'awslogs-group': !Ref LogGroup
              'awslogs-region': !Ref AWS::Region
              'awslogs-stream-prefix': 'ecs'
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      # TaskRoleArn: !GetAtt ApplicationTaskRole.Arn
      Volumes:
        - Name: Data
          EFSVolumeConfiguration:
# Enforcement of ownership not needed; see DataVolumeAccessPoint above
#            AuthorizationConfig:
#              AccessPointId: !Ref DataVolumeAccessPoint
#              IAM: ENABLED
            FilesystemId: !Ref DataVolume
# Enforcement of ownership not needed; see above
#            TransitEncryption: ENABLED

  LoadBalancerTarget:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: /livez
      HealthCheckIntervalSeconds: 300
      HealthCheckTimeoutSeconds: 120
      Matcher:
        HttpCode: '200,301,302'
      Port: 80
      Protocol: HTTP
      TargetType: ip
      UnhealthyThresholdCount: 4
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'

  LoadBalancerListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Conditions:
        - Field: host-header
          Values:
            - !Ref Hostname
      Actions:
        - Order: 1
          Type: forward
          TargetGroupArn: !Ref LoadBalancerTarget
      ListenerArn:
        'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerListener'
      Priority: !Ref LoadBalancerRulePriority

  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Mailpit
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300
          - Type: AAAA
            TTL: 300
        RoutingPolicy: WEIGHTED
      Name: !Ref ServiceDiscoveryName
      NamespaceId:
        'Fn::ImportValue': !Sub '${ServiceDiscoveryStack}-Id'
      Tags:
        - Key: Project
          Value: !Ref Project

  Application:
    Type: AWS::ECS::Service
    DependsOn:
      - LoadBalancerListenerRule
    Properties:
      Cluster:
        'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-FargateCluster'
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: Mailpit
          ContainerPort: 8025
          TargetGroupArn: !Ref LoadBalancerTarget
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          # Do not use all private subnets, only subnet A as this is the only subnet with a NAT gateway
          # Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
          Subnets:
            - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'
          SecurityGroups:
            - !GetAtt VolumeAccess.GroupId
            - 'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerSecurityGroup'
            - 'Fn::ImportValue': !Sub '${ParentVPCStack}-DefaultSecurityGroup'  # Access to internet
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      TaskDefinition: !Ref ApplicationTaskDefinition


Outputs:
  EcsService:
    Description: ECS Service
    Value: !Ref Application
    Export:
      Name: !Sub '${AWS::StackName}-EcsService'
  Cluster:
    Description: ECS Cluster
    Value:
      'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-FargateCluster'
    Export:
      Name: !Sub '${AWS::StackName}-Cluster'
