AWSTemplateFormatVersion: '2010-09-09'
Description: 'MySQL Docker container'

Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  LogGroupRetentionTime:
    Description: The retention time in days.
    Type: Number
    Default: 731
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  DBRootPassword:
    Description: The superuser credentials to access the database
    Type: String
    NoEcho: true
  DBUsername:
    Description: The user name to access the database
    Type: String
    NoEcho: true
  DBPassword:
    Description: The credentials to access the database
    Type: String
    NoEcho: true
  DBName:
    Description: The database name
    Type: String
  ServiceDiscoveryName:
    Description: The name under which this service will be registered at Service Discovery
    Type: String
  Cpu:
    Description: The number of CPU units used by this application. 1024 is equivalent to 1 CPU.
    Type: String
    AllowedValues: [256, 512, 1024, 2048, 4096]
  Memory:
    Description: The memory (in MBytes) to allocate for this application.
    Type: String
  ContainerClusterAlbStack:
    Description: Stack name of Fargate container stack
    Type: String
  ServiceDiscoveryStack:
    Description: Stack name of service discovery stack
    Type: String
  Environment:
    Description: The current environment (e.g. branch name)
    Type: String
  Project:
    Description: The project name.
    Type: String

Resources:
  ApplicationAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to access application
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      Tags:
        - Key: Project
          Value: !Ref Project

  ApplicationAccessSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ApplicationAccess
      IpProtocol: -1
      SourceSecurityGroupId: !Ref ApplicationAccess

  ApplicationAccessSelfEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref ApplicationAccess
      IpProtocol: -1
      DestinationSecurityGroupId: !Ref ApplicationAccess

  VolumeAccess:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to access volumes
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      Tags:
        - Key: Project
          Value: !Ref Project

  VolumeAccessSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref VolumeAccess
      IpProtocol: -1
      SourceSecurityGroupId: !Ref VolumeAccess

  VolumeAccessSelfEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref VolumeAccess
      IpProtocol: -1
      DestinationSecurityGroupId: !Ref VolumeAccess

  DataVolume:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: !Sub 'MySQL ${Environment}'
        - Key: Project
          Value: !Ref Project

  DataVolumeMountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref DataVolume
      SecurityGroups:
        - !GetAtt VolumeAccess.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'

  DataVolumeMountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref DataVolume
      SecurityGroups:
        - !GetAtt VolumeAccess.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPrivate'

  DataVolumeMountTargetC:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref DataVolume
      SecurityGroups:
        - !GetAtt VolumeAccess.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetCPrivate'

# Application does not need any access to AWS services; uncomment block if required
#  ApplicationTaskRole:
#    Type: AWS::IAM::Role
#    Properties:
#      Description: Application's permissions
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service: ecs-tasks.amazonaws.com
#            Action: sts:AssumeRole
#      ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Provides access to other AWS service resources that are required to run Amazon ECS tasks
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref LogGroupRetentionTime

  ApplicationTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - DataVolumeMountTargetA
      - DataVolumeMountTargetB
      - DataVolumeMountTargetC
    Properties:
      ContainerDefinitions:
        - Name: MySQL
          Image: mysql:8
          Environment:
            - Name: MYSQL_ROOT_PASSWORD
              Value: !Ref DBRootPassword
            - Name: MYSQL_USER
              Value: !Ref DBUsername
            - Name: MYSQL_PASSWORD
              Value: !Ref DBPassword
            - Name: MYSQL_DATABASE
              Value: !Ref DBName
          MountPoints:
            - ContainerPath: /var/lib/mysql
              SourceVolume: Data
          PortMappings:
            - ContainerPort: 3306
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              'awslogs-group': !Ref LogGroup
              'awslogs-region': !Ref AWS::Region
              'awslogs-stream-prefix': 'ecs'
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      # TaskRoleArn: !GetAtt ApplicationTaskRole.Arn
      Volumes:
        - Name: Data
          EFSVolumeConfiguration:
            FilesystemId: !Ref DataVolume

  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: MySQL database
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 300
          - Type: AAAA
            TTL: 300
        RoutingPolicy: WEIGHTED
      Name: !Ref ServiceDiscoveryName
      NamespaceId:
        'Fn::ImportValue': !Sub '${ServiceDiscoveryStack}-Id'
      Tags:
        - Key: Project
          Value: !Ref Project

  Application:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-FargateCluster'
      DesiredCount: 1
      EnableECSManagedTags: true
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          # Do not use all private subnets, only subnet A as this is the only subnet with a NAT gateway
          # Subnets: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
          Subnets:
            - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'
          SecurityGroups:
            - !GetAtt ApplicationAccess.GroupId
            - !GetAtt VolumeAccess.GroupId
            - 'Fn::ImportValue': !Sub '${ParentVPCStack}-DefaultSecurityGroup'  # Access to internet
      ServiceRegistries:
        - RegistryArn: !GetAtt ServiceDiscovery.Arn
      TaskDefinition: !Ref ApplicationTaskDefinition


Outputs:
  ApplicationAccess:
    Description: Security group to access the application
    Value: !GetAtt ApplicationAccess.GroupId
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationAccess'
