AWSTemplateFormatVersion: '2010-09-09'
Description: DNS records including certificate for Application load balancer

Parameters:
  Domain:
    Description: The domain where this application should be reachable at.
    Type: String
  Route53HostedZone:
    Description: The Route53 hosted zone ID
    Type: String
  ContainerClusterAlbStack:
    Description: 'Stack name of parent container cluster and load balancer stack.'
    Type: String
  Project:
    Description: The project name.
    Type: String

Resources:
  DnsRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref Domain
      HostedZoneId: !Ref Route53HostedZone
      Type: A
      AliasTarget:
        DNSName:
          'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerDnsName'
        HostedZoneId:
          'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerCanonicalHostedZoneID'

  DnsRecordSetV6:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref Domain
      HostedZoneId: !Ref Route53HostedZone
      Type: AAAA
      AliasTarget:
        DNSName:
          'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerDnsName'
        HostedZoneId:
          'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerCanonicalHostedZoneID'

  LoadBalancerListenerHttpsCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref Domain
      DomainValidationOptions:
        - DomainName: !Ref Domain
          HostedZoneId: !Ref Route53HostedZone
      ValidationMethod: DNS
      Tags:
        - Key: Project
          Value: !Ref Project

  LoadBalancerListenerCertificate:
    Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
    Properties:
      Certificates:
        - CertificateArn: !Ref LoadBalancerListenerHttpsCertificate
      ListenerArn:
        'Fn::ImportValue': !Sub '${ContainerClusterAlbStack}-LoadBalancerListener'
