AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bastion host'

Parameters:
  Project:
    Description: The project name.
    Type: String
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  ParentDatabaseStack:
    Description: 'Stack name of parent database stack.'
    Type: String

Resources:
  PublicAccessSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Public access
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIpv6: '::/0'

  BastionHost:
    Type: 'AWS::EC2::Instance'
    Properties:
      #ImageId: ami-0bd39c806c2335b95  # Amazon Linux 2 for x86 in eu-central-1
      #InstanceType: t3.nano
      ImageId: ami-011c2803cfd207fca  # Amazon Linux 2 for AMI in eu-central-1
      InstanceType: t4g.nano
      SecurityGroupIds:
        - 'Fn::ImportValue': !Sub '${ParentDatabaseStack}-DBInstanceSecurityGroupId'
        - !GetAtt PublicAccessSecurityGroup.GroupId
      SubnetId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPublic'
      Tags:
        - Key: Name
          Value: Bastion Host for data storage PostgreSQL

Outputs:
  InstanceID:
    Description: Instance ID
    Value: !Ref BastionHost
  AvailabilityZone:
    Description: Availability Zone
    Value: !GetAtt BastionHost.AvailabilityZone
  PublicIp:
    Description: Public IP address
    Value: !GetAtt BastionHost.PublicIp
