AWSTemplateFormatVersion: '2010-09-09'
Description: 'SFTP server'

Parameters:
  Project:
    Description: The project name.
    Type: String
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  HostedZoneName:
    Description: The Route53 hosted zone name
    Type: String
    Default: ''
  DomainName:
    Description: The (sub)domain of the SFTP server
    Type: String
    Default: ''

Conditions:
  CreateDnsRecord: !Not [!Equals [!Ref HostedZoneName, '']]

Resources:
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  EIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  Firewall:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Firewall for SFTP server'
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  LoggingAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Write-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogStreams'
                  - 'logs:CreateLogGroup'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:log-group:/aws/transfer/*'

  Server:
    Type: AWS::Transfer::Server
    Properties:
      Domain: S3
      EndpointType: VPC
      EndpointDetails:
        AddressAllocationIds:
          - !GetAtt EIP.AllocationId
          - !GetAtt EIP2.AllocationId
        SecurityGroupIds:
          - !GetAtt Firewall.GroupId
        SubnetIds:
          # Two subnets to increase availability
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPublic'
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPublic'
        VpcId:
          'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
      IdentityProviderType: SERVICE_MANAGED
      LoggingRole: !GetAtt LoggingAccess.Arn
      Protocols:
        - SFTP
      SecurityPolicyName: TransferSecurityPolicy-2020-06
      Tags:
        - Key: Project
          Value: !Ref Project

  ServerDomain:
    Type: AWS::Route53::RecordSet
    Condition: CreateDnsRecord
    Properties:
      Name: !Ref DomainName
      Type: CNAME
      ResourceRecords:
        - !Sub '${Server.ServerId}.server.transfer.${AWS::Region}.amazonaws.com'
      TTL: 300
      HostedZoneName: !Sub '${HostedZoneName}.'


Outputs:
  ServerId:
    Value: !GetAtt Server.ServerId
    Description: Server ID
    Export:
      Name: !Sub '${AWS::StackName}-ServerId'
  Endpoint:
    Value: !Sub '${Server.ServerId}.server.transfer.${AWS::Region}.amazonaws.com'
    Description: Endpoint
    Export:
      Name: !Sub '${AWS::StackName}-Endpoint'
