AWSTemplateFormatVersion: '2010-09-09'
Description: Encryption key to protect S3 data

Parameters:
  Project:
    Description: The project name.
    Type: String

Resources:
  S3Key:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Key to protect S3 data
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Allow direct access to key metadata to the account
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow access through S3 for all principals in the account that are authorized to use S3
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
            Condition:
              StringEquals:
                kms:CallerAccount: !Ref 'AWS::AccountId'
                kms:ViaService: !Sub s3.${AWS::Region}.amazonaws.com
      Tags:
        - Key: Project
          Value: !Ref Project

  S3KeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/custom/s3
      TargetKeyId: !Ref S3Key

Outputs:
  ID:
    Description: 'Key ID'
    Value: !Ref S3Key
    Export:
      Name: !Sub '${AWS::StackName}-ID'
  Alias:
    Description: 'Alias'
    Value: !Ref S3KeyAlias
    Export:
      Name: !Sub '${AWS::StackName}-Alias'
  Arn:
    Description: 'Arn'
    Value: !GetAtt S3Key.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
