AWSTemplateFormatVersion: '2010-09-09'
Description: 'Storage for Lambda functions'

Parameters:
  Project:
    Description: The project name.
    Type: String
  User:
    Description: The user name.
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref Project

Outputs:
  Name:
    Description: 'Name'
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-Name'
  Arn:
    Description: 'Arn'
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
