AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda to deliver index.html if a folder was requested'

# Lambda function for delivering index.html if a folder was requested (which PIP usually does)
# Source: https://forestry.io/blog/adding-dns-and-edge-functions-to-our-cloudformation-stack/

Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
                - 'edgelambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          'use strict';
          exports.handler = (event, context, callback) => {
            // Extract the request from the CloudFront event that is sent to Lambda@Edge
            var request = event.Records[0].cf.request;
          
            // Extract the URI from the request
            var olduri = request.uri;
          
            // Match any '/' that occurs at the end of a URI. Replace it with a default index
            var newuri = olduri.replace(/\/$/, '\/index.html');
          
            // Replace the received URI with the URI that includes the index page
            request.uri = newuri;
          
            // Return to CloudFront
            return callback(null, request);
          };
      Handler: 'index.handler'
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Runtime: 'nodejs12.x'
      Timeout: 5

  VersionedLambdaFunction:
    Type: 'AWS::Lambda::Version'
    Properties:
      FunctionName: !Ref LambdaFunction

Outputs:
  Arn:
    Value: !Ref VersionedLambdaFunction
    Description: Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
