AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket for S3 backed repository'

# Template: https://github.com/widdix/aws-cf-templates/blob/master/static-website/static-website.yaml

Parameters:
  DomainName:
    Description: 'The domain name'
    Type: String
  AcmCertificateArn:
    Description: 'ARN of domain name certificate in us-east-1'
    Type: String
  HostedZoneId:
    Description: 'ID of hosted zone'
    Type: String
  LambdaArn:
    Description: 'ARN of Lambda@Edge function'
    Type: String

Resources:
  # Once upon a time there was a bucket 'Bucket',
  # but an Accenture policy said: "That's not good", as it was public.
  # 'Bucket2' is it's successor, this time private
  # with CloudFront as public interface.
  # As renaming of resources does not work in CloudFormation,
  # we'll leave it as 'Bucket2'.
  Bucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DomainName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref DomainName

  Bucket2Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref Bucket2
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${Bucket2}/*'
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Comment: !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600 # in seconds
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400 # in seconds
          MinTTL: 60 # in seconds
          TargetOriginId: s3origin
          ViewerProtocolPolicy: 'redirect-to-https'
          LambdaFunctionAssociations:
            - EventType: 'origin-request'
              LambdaFunctionARN: !Ref LambdaArn
        DefaultRootObject: ''
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt 'Bucket2.RegionalDomainName'
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:733910457727:certificate/4e2f3a46-fa18-4443-b8a8-09304e732a6d'
          MinimumProtocolVersion: 'TLSv1.2_2018'
          SslSupportMethod: 'sni-only'

  Route53RecordIPv4:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref DomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'

  Route53RecordIPv6:
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref DomainName
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # Magic CloudFront number
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'

  UploadPythonPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Grants upload rights to Python repository
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource:
              - !Join [ '', [ 'arn:aws:s3:::', !Ref Bucket2, '/python/*' ]]
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource:
              - !Join [ '', [ 'arn:aws:s3:::', !Ref Bucket2 ]]

Outputs:
  BucketName:
    Value: !Ref Bucket2
    Description: Repository bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  Arn:
    Value: !GetAtt Bucket2.Arn
    Description: Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
