AWSTemplateFormatVersion: '2010-09-09'
Description: 'Web interface to provide data'

Parameters:
  Project:
    Description: The project name.
    Type: String
  User:
    Description: The user name.
    Type: String
  ApplicationName:
    Description: The name of the application
    Type: String
  UploadStorageStack:
    Description: The stack name of the stack which set up the Batch queue.
    Type: String
  SourceCodeFilename:
    Description: The file name containing the source code, uploaded to S3
    Type: String
  HandlerFunction:
    Description: The name of the Python function which handles Lambda calls
    Type: String
  MemorySize:
    Description: The amount of memory that the function has access to.
    Type: Number
    Default: 128
  Timeout:
    Description: The amount of time that the function is allowed to run before being stopped.
    Type: Number
    Default: 20
  Runtime:
    Description: The runtime the function requires.
    Type: String
  DbHostname:
    Description: The host name of the database
    Type: String
  DbPort:
    Description: The port of the database
    Type: String
  DbDatabase:
    Description: The name of the database
    Type: String
  DbUsername:
    Description: The user name to access the database
    Type: String
  DbPasswordParam:
    Description: The name of the SSM secure string which contains the password to access the database
    Type: String
  LogsRetentionInDays:
    Description: 'Specifies the number of days you want to retain log events.'
    Type: Number
    Default: 400
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String
  DatabaseStack:
    Description: The stack name of the database stack.
    Type: String
  AlarmNotificationsStack:
    Description: Stack name of alarm notifications.
    Type: String

Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: Read-SSM-Parameters
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${DbPasswordParam}'

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': !Sub '${UploadStorageStack}-Name'
        S3Key: !Ref SourceCodeFilename
      Environment:
        Variables:
          DB_HOSTNAME: !Ref DbHostname
          DB_PORT: !Ref DbPort
          DB_DATABASE: !Ref DbDatabase
          DB_PASSWORD_PARAM: !Ref DbPasswordParam
          DB_USERNAME: !Ref DbUsername
      Handler: !Ref HandlerFunction
      MemorySize: !Ref MemorySize
      Role: !GetAtt LambdaFunctionRole.Arn
      Runtime: !Ref Runtime
      Timeout: !Ref Timeout
      VpcConfig:
        SecurityGroupIds:
          - 'Fn::ImportValue': !Sub '${DatabaseStack}-DBInstanceSecurityGroupId'  # Access to database
          - 'Fn::ImportValue': !Sub '${ParentVPCStack}-DefaultSecurityGroup'  # Access to VPC endpoint to SSM
        SubnetIds: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
      Tags:
        - Key: Project
          Value: !Ref Project

  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      # Logs for Lambda function must follow a specific schema
      LogGroupName: !Join ['', ['/aws/lambda/', !Ref LambdaFunction]]
      RetentionInDays: !Ref LogsRetentionInDays

  ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: 'ERROR'
      LogGroupName: !Ref Logs
      MetricTransformations:
        - MetricName: Errors
          MetricNamespace: !Sub 'Lambda/${ApplicationName}'
          MetricValue: 1
          DefaultValue: 0

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: !Sub '${ApplicationName} reported an error'
      ActionsEnabled: true
      Namespace: !Sub 'Lambda/${ApplicationName}'
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 0.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 300
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

  LambdaError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Errors in Lambda function
      ActionsEnabled: true
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunction
      MetricName: Errors
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 60
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'

  LambdaThrottles:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Errors in Lambda function
      ActionsEnabled: true
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunction
      MetricName: Throttles
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1.0
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Period: 60
      TreatMissingData: notBreaching
      AlarmActions:
        - 'Fn::ImportValue': !Sub '${AlarmNotificationsStack}-Arn'


Outputs:
  Name:
    Description: 'Name'
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub '${AWS::StackName}-Name'
  Arn:
    Description: 'Arn'
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-Arn'
