AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Endpoint to allow access S3 from private subnets

Parameters:
  VPCStack:
    Description: The stack name containing the VPC definitions.
    Type: String

Resources:
  S3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'
      RouteTableIds: !Split [',', !Join [',', ['Fn::ImportValue': !Sub '${VPCStack}-RouteTablesPrivate', 'Fn::ImportValue': !Sub '${VPCStack}-RouteTablesPublic']]]
      ServiceName: !Join ['', ['com.amazonaws.', !Ref 'AWS::Region', '.s3']]
      VpcId:
        'Fn::ImportValue': !Sub '${VPCStack}-VPC'
