AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Endpoint to allow access SSM from private subnets

Parameters:
  ParentVPCStack:
    Description: The stack name containing the VPC definitions.
    Type: String

Resources:
  SsmEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-DefaultSecurityGroup'
      ServiceName: !Join ['', ['com.amazonaws.', !Ref 'AWS::Region', '.ssm']]
      SubnetIds: !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
      VpcEndpointType: Interface
      VpcId:
        'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'
