AWSTemplateFormatVersion: '2010-09-09'
Description: 'Code artifact for Maven and Python'

Parameters:
  Project:
    Description: The project name.
    Type: String
  DomainName:
    Description: The name of the domain that contains the repository.
    Type: String
  RepositoryName:
    Description: The name of the repository.
    Type: String
  GrantedAccounts:
    Description: The list of accounts which should get read-only access
    Type: CommaDelimitedList

Resources:
  Domain:
    Type: 'AWS::CodeArtifact::Domain'
    Properties:
      DomainName: !Ref DomainName
      PermissionsPolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codeartifact:DescribeDomain
              - codeartifact:GetAuthorizationToken
              - codeartifact:GetDomainPermissionsPolicy
              - codeartifact:ListRepositoriesInDomain
              - sts:GetServiceBearerToken
            Effect: Allow
            Principal:
              AWS: !Ref GrantedAccounts
            Resource: '*'
      Tags:
        - Key: Project
          Value: !Ref Project

  PypiRepository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: pypi-store
      Description: Python Package Index
      DomainName: !GetAtt Domain.Name
      ExternalConnections:
        - public:pypi
      Tags:
        - Key: Project
          Value: !Ref Project

  NpmRepository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: npm-store
      Description: npm public registry
      DomainName: !GetAtt Domain.Name
      ExternalConnections:
        - public:npmjs
      Tags:
        - Key: Project
          Value: !Ref Project

  MavenRepository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: maven-central-store
      Description: Maven Central
      DomainName: !GetAtt Domain.Name
      ExternalConnections:
        - public:maven-central
      Tags:
        - Key: Project
          Value: !Ref Project

  GradlePluginsRepository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: gradle-plugins-store
      Description: Gradle plugins repository
      DomainName: !GetAtt Domain.Name
      ExternalConnections:
        - public:maven-gradleplugins
      Tags:
        - Key: Project
          Value: !Ref Project

  Repository:
    Type: 'AWS::CodeArtifact::Repository'
    Properties:
      RepositoryName: !Ref RepositoryName
      Description: Our own custom artifacts
      DomainName: !GetAtt Domain.Name
      PermissionsPolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - codeartifact:DescribePackageVersion
              - codeartifact:DescribeRepository
              - codeartifact:GetPackageVersionReadme
              - codeartifact:GetRepositoryEndpoint
              - codeartifact:ListPackageVersionAssets
              - codeartifact:ListPackageVersionDependencies
              - codeartifact:ListPackageVersions
              - codeartifact:ListPackages
              - codeartifact:ReadFromRepository
            Effect: Allow
            Principal:
              AWS: !Ref GrantedAccounts
            Resource: '*'
      Upstreams:
        - !GetAtt PypiRepository.Name
        - !GetAtt NpmRepository.Name
        - !GetAtt MavenRepository.Name
        - !GetAtt GradlePluginsRepository.Name
      Tags:
        - Key: Project
          Value: !Ref Project


Outputs:
  Name:
    Value: !GetAtt Repository.Name
    Description: Repository name
    Export:
      Name: !Sub '${AWS::StackName}-Name'
  DomainName:
    Value: !GetAtt Repository.DomainName
    Description: Domain name
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
  Maven:
    Value: !Sub 'https://${Repository.DomainName}-${Repository.DomainOwner}.d.codeartifact.${AWS::Region}.amazonaws.com/maven/${Repository.Name}/'
    Description: Maven repository
    Export:
      Name: !Sub '${AWS::StackName}-Maven'
  PyPI:
    Value: !Sub 'https://aws:CODEARTIFACT_AUTH_TOKEN@${Repository.DomainName}-${Repository.DomainOwner}.d.codeartifact.${AWS::Region}.amazonaws.com/pypi/${Repository.Name}/'
    Description: PyPI repository
    Export:
      Name: !Sub '${AWS::StackName}-PyPI'
